controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

register_user:
    path: /users/register
    controller: App\Controller\RegisterUserController
    methods: [POST]
